document.addEventListener("DOMContentLoaded", () => {
  document
    .querySelectorAll(".color")
    .forEach(
      (color) =>
        (color.style.backgroundColor = color.getAttribute("data-color"))
    );

  const topicElement = document.querySelector(".paint__topic");

  const topics = [
    "beef",
    "phone",
    "controller",
    "bracelet",
    "sun glasses",
    "computer",
    "rubber band",
    "spring",
    "sharpie",
    "model car",
    "slipper",
    "table",
    "eye liner",
    "fake flowers",
    "bookmark",
    "pillow",
    "canvas",
    "book",
    "scotch tape",
    "cup",
    "doll",
    "shovel",
    "conditioner",
    "seat belt",
    "brocolli",
    "puddle",
    "keys",
    "tooth picks",
    "box",
    "outlet",
    "mouse pad",
    "monitor",
    "candle",
    "wagon",
    "balloon",
    "hanger",
    "sailboat",
    "chapter book",
    "tire swing",
    "bowl",
    "drill press",
    "sofa",
    "car",
    "soap",
    "floor",
    "nail file",
    "television",
    "soda can",
    "grid paper",
    "clamp",
    "shampoo",
    "rusty nail",
    "sponge",
    "paper",
    "CD",
    "pants",
    "purse",
    "chocolate",
    "sticky note",
    "speakers",
    "bananas",
    "camera",
    "headphones",
    "nail clippers",
    "tv",
    "magnet",
    "charger",
    "towel",
    "shirt",
    "thermostat",
    "socks",
    "mirror",
    "bed",
    "cork",
    "lamp shade",
    "knife",
    "fork",
    "glow stick",
    "candy wrapper",
    "face wash",
    "flowers",
    "paint brush",
    "pool stick",
    "ice cube tray",
    "eraser",
    "blouse",
    "photo album",
    "pen",
    "white out",
    "twister",
    "washing machine",
    "rug",
    "clothes",
    "credit card",
    "greeting card",
    "coasters",
    "bottle cap",
    "apple",
    "toothbrush",
    "tomato",
    "picture frame",
    "tree",
    "cookie jar",
    "checkbook",
    "air freshener",
    "toilet",
    "lotion",
    "bag",
    "blanket",
    "mp3 player",
    "sketch pad",
    "ipod",
    "bow",
    "bread",
    "vase",
    "clay pot",
    "newspaper",
    "sidewalk",
    "helmet",
    "toe ring",
    "USB drive",
    "screw",
    "needle",
    "wallet",
    "cinder block",
    "stop sign",
    "chair",
    "thread",
    "tissue box",
    "stockings",
    "hair tie",
    "shoes",
    "rubber duck",
    "flag",
    "lamp",
    "shawl",
    "leg warmers",
    "sandal",
    "food",
    "house",
    "fridge",
    "shoe lace",
    "button",
    "plate",
    "twezzers",
    "cell phone",
    "deodorant",
    "teddies",
    "drawer",
    "glass",
    "piano",
    "soy sauce packet",
    "window",
    "video games",
    "glasses",
    "keyboard",
    "thermometer",
    "playing card",
    "radio",
    "hair brush",
    "truck",
    "carrots",
    "mop",
    "chalk",
    "boom box",
    "lip gloss",
    "plastic fork",
    "spoon",
    "ring",
    "pencil",
    "buckle",
    "cat",
    "zipper",
    "milk",
    "watch",
    "street lights",
    "toothpaste",
    "lace",
    "couch",
    "money",
    "sand paper",
    "remote",
    "desk",
    "door",
    "key chain",
    "bottle",
    "packing peanuts",
    "perfume",
    "water bottle",
    "clock",
  ];

  const pickTopicToDraw = () => {
    topicElement.textContent =
      topics[Math.floor(Math.random() * topics.length)];
  };
  pickTopicToDraw();
});
